version: '3.8'

volumes:
  mysql_local_data:
  node_modules:
  vendor:

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: db
    hostname: db
    environment:
      MYSQL_DATABASE: store
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_local_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysqldb
